# Porta del server a cui connettersi
PORT = 9070

# Indirizzo del server a cui connettersi
HOST = localhost

# dimenzione del buffer per la comunicazione tcp
BUFFER_SIZE = 1024

#dimenzione del datacgram packet per la comunicazione udp
DATAGRAM_PACKET_SIZE = 8192
