# Porta su cui il server ascolta
PORT = 9070

# i minuti della partita
TIMEOUT = 5

# i minuti per il controllo del log
TIMECHECKLOG = 2

# inizio dei salvataggi automatici dei file di log
TIMESTARTLOG = 1

# file dove salvare le partite giocate
FILE_PARTITE = partite_storiche

# file dove salvare i profili dei giocatori
FILE_PROFILI = log_profili.json

# cartella dove salvare i file di log
CARTELLA_LOG = logs

# numero massimo di player nella classifica
MAX_CLASSIFICA = 300